apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
  name: scaling-study-efa-hossen1-08142023
  region: us-east-1
  version: "1.27"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'

availabilityZones: ["us-east-1a", "us-east-1b"]
managedNodeGroups:
  - name: scaling-study-efa-hossen1-08142023
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    minSize: 8
    maxSize: 50
    desiredCapacity: 8
    efaEnabled: true
    placement:
      groupName: eks-efa-testing
    labels: { "flux-operator": "true" }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/scaling-study-efa: "owned"
      Name: 'scaling-study-efa-hossen1-08142023'
    propagateASGTags: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    